import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const englisch = localFont({
  src: [{
    path:'../fonts/Englisch.otf',
    weight:'800',
    style: 'normal'
  }],
  variable: '--font-englisch'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-background-100 ' + englisch.className}>{children}</body>
    </html>
  );
}
